/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_speccall_util_Native */

#ifndef _Included_com_example_speccall_util_Native
#define _Included_com_example_speccall_util_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_speccall_util_Native
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_speccall_util_Native_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
